### ISSUE TITLE
schema

### ISSUE THREAD

**Issue by pedromorgan** [ts2/ts2-sim-server#14]
Arrh!! shouted @pedromorgan on @npiganeau behalf..

We need to document stuff,

Never used it but might http://json-schema.org work ??

This would be cool as it would also work as an api validator etc ??

# ws interface
- we need to document the raltime json schema first.. as its a realtime system l-)

**Comment by npiganeau** [comment]
Documentation is foreseen by end of May. I'll have a look at JSON schema.

**Comment by pedromorgan** [comment]
Well another one i want to try with ts2, Its looks like a pain in the but, but basically we describe what each "json.bit" is..
eg service.json, route.json and then can validate against..

**Comment by npiganeau** [comment]
Documentation in docs folder
