### ISSUE TITLE
Parts of a route are not disabled after train passage if there is an intermediary signal

### ISSUE THREAD

**Issue by Sharpe49** [ts2/ts2-sim-server#36]
On the attached map, if there is an intermediary signal on a route, parts of this route are not disabled when the train passes.
[gretz-armainvilliers.zip](https://github.com/ts2/ts2-sim-server/files/3571994/gretz-armainvilliers.zip)

Train for the test : the first one coming from Coulommiers

**Comment by Sharpe49** [comment]
Missing file due to modified signals :
[FR_BAL.zip](https://github.com/ts2/ts2-sim-server/files/3637632/FR_BAL.zip)

**Comment by graeme-defty** [comment]
I would be happy to fix this but as I am not familiar with French signalling I am not sure what the problem actually is.

Is it possible to cut the simulation down by removing what does not relate to the problem?

**Comment by npiganeau** [comment]
Ok. I can see it in this simulation: [fr-test.zip](https://github.com/ts2/ts2-sim-server/files/3726099/fr-test.zip), when setting a route directly from 1st to 3rd signal. 

Similarly, when the route is persistent, the middle signal is deactivated whereas it shouldn't. I suppose this is related.

I'll investigate.

**Comment by npiganeau** [comment]
Fixed in master
