### ISSUE TITLE
New 'places' type is missing from the 'dump simulation' call

### ISSUE THREAD

**Issue by tomzorz** [ts2/ts2-sim-server#6]
![image](https://user-images.githubusercontent.com/6363312/56971692-0076c580-6b6a-11e9-9323-597d03a96e70.png)

**Comment by npiganeau** [comment]
Places are actually TrackItems. In the simulation dump they are TrackItem 19, 20 and 21.

The place list and place show is just an index by place code instead of ID.

I will add them to the trackItems list and show for consistency.

**Comment by tomzorz** [comment]
Ah, thanks! :)
